# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc9c7abd4d81bdc68b855e06711009622e1266c5afd01dda2269b2e6e7679d06078e7deed0f0f7791c11e63b4c3756e7807bc6d65b5c8070a5d13dbea02f52f3

test:
  secret_key_base: 3ec231c27b26f459b77873111ec143fbc79a3ba3443700cae8091eed06219bad410fbb21ad69228a7ce0716f2b8f802f31b163e9bf95ddc92df19376aadcf503

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
